name: Setup Conda Environment and Run Tests

on:
  push:
    branches:
      - py3.9-update
      - main
  pull_request:
    branches:
      - py3.9-update
      - main

jobs:
  setup-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.9  # Updated to Python 3.9 as per your branch name
        activate-environment: geoCosiCorr3D
        environment-file: geoCosiCorr3D.yml
        auto-activate-base: false

    - name: Configure LD_LIBRARY_PATH
      run: echo "LD_LIBRARY_PATH=$(pwd)/lib/:$LD_LIBRARY_PATH" >> $GITHUB_ENV

    - name: Activate geoCosiCorr3D environment
      run: conda activate geoCosiCorr3D

    - name : Run Tests
      run: pytest test
